spring.application.name=HelpWithTEACCH

# DATABASE
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SERVER
server.port=${PORT:8080}

# ADMIN DEFAULT
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.admin.nombres=${ADMIN_NOMBRES:Administrador}
app.admin.apellidos=${ADMIN_APELLIDOS:Sistema}

# JWT
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION:86400000}

# IA SERVICE
ia.service.url=${IA_SERVICE_URL}